package com.sample
 
import communication.Attribute;
import communication.Question;


rule "asktype"
    when
    then
      Question.Ask("type");
end

rule "askppl"
    when
    then
      Question.Ask("people");
end

rule "formanyppljustdixit"
	when
		a: Attribute(Name("people"), GreaterThan(6));
	then
		Question.Ask("offer_dixit");
end

rule "new attr"
	when
		a: Attribute();
	then
		System.out.println("new Attribute! type: " + a.Name() + ", value: " + a.Value());
end

rule "game found"
	when
		a: Attribute(Name("game"), Equals(true));
	then
		System.out.println("Finished!");
		drools.halt();
end
